version: '3'

networks:
  app:
    driver: bridge

services:
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: back
    restart: on-failure
    environment:
      - TG_TOKEN=
      - GIGA_TOKEN=
    networks:
      - app
